services:
  - type: web
    name: employee-checklist
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
    domains:
      - employee-checklist.onrender.com
    disk:
      name: employee-data
      mountPath: /data
      sizeGB: 1
